# Generated by Django 3.0.6 on 2020-07-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30, null=True)),
                ('sub_category', models.CharField(max_length=30, null=True)),
                ('subject', models.CharField(max_length=50, null=True)),
                ('complain_1', models.TextField(null=True)),
            ],
        ),
    ]
